development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  firebase_project_id: <%= ENV["FIREBASE_PROJECT_ID"] %>
  firebase_web_api_key: <%= ENV["FIREBASE_WEB_API_KEY"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  firebase_project_id: <%= ENV["FIREBASE_PROJECT_ID"] %>
  firebase_web_api_key: <%= ENV["FIREBASE_WEB_API_KEY"] %>
